name: flix_movie
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: '>=3.1.2 <4.0.0'

dependencies:
    cloud_firestore: ^4.9.2
    cupertino_icons: ^1.0.2
    dio: ^5.3.3
    firebase_auth: ^4.10.0
    firebase_core: ^2.16.0
    firebase_storage: ^11.2.7
    flutter:
        sdk: flutter
    flutter_riverpod: ^2.4.0
    freezed_annotation: ^2.4.1
    go_router: ^11.1.2
    google_fonts: ^6.1.0
    intl: ^0.18.1
    json_annotation: ^4.8.1
    path: ^1.8.3
    riverpod_annotation: ^2.1.5

dev_dependencies:
    build_runner: ^2.4.6
    custom_lint: ^0.5.3
    flutter_lints: ^2.0.0
    flutter_test:
        sdk: flutter
    freezed: ^2.4.2
    json_serializable: ^6.7.1
    riverpod_generator: ^2.3.2
    riverpod_lint: ^2.1.0

flutter:
    uses-material-design: true

    assets:
        - assets/
